name: CI
on:
  push:
    branches:
      - "dev"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm ci
        run: |
          npm ci
      - name: npm run test
        run: |
          npm run test
      - name: npm run build
        run: |
          npm run build
